export const GET_DEVICE_TELEMETRY = "GET_DEVICE_TELEMETRY";
export const GET_DEVICES_FOR_TILES = "GET_DEVICES_FOR_TILES";
export const STORE_WEATHER_DEVICE_TELEMETRY = "STORE_WEATHER_DEVICE_TELEMETRY";
